// Encodes binary assets as base64 data URLs into a JS module for bundling.
const fs = require('fs');
const path = require('path');
const HERE = __dirname;

function dataUrl(p, mime) {
  const b = fs.readFileSync(p);
  console.log(path.basename(p), (b.length / 1048576).toFixed(2), 'MB');
  return `data:${mime};base64,${b.toString('base64')}`;
}

const out = `// generated by hd-embed.js — do not edit
export const SUMO_GLB = "${dataUrl(path.join(HERE, 'hoshoryu.glb'), 'model/gltf-binary')}";
export const TEX_WATERNORMALS = "${dataUrl(path.join(HERE, 'waternormals.jpg'), 'image/jpeg')}";
export const TEX_GRASS = "${dataUrl(path.join(HERE, 'three-repo/examples/textures/terrain/grasslight-big.jpg'), 'image/jpeg')}";
`;
fs.writeFileSync(path.join(HERE, 'hd-assets.js'), out);
console.log('hd-assets.js written', (fs.statSync(path.join(HERE, 'hd-assets.js')).size / 1048576).toFixed(1), 'MB');
